package com.bosicc.cluedo.pojo;

import java.io.Serializable;
import java.util.ArrayList;

import android.content.res.Resources;

public class GamePOJO implements Serializable{
	/**
	 * Autogenerated Version UID
	 */
	private static final long serialVersionUID = 3678689194557638298L;
	
	private int version = -1;
	 
	public int NumberOfPlayers;
	public int YourPlayer;
	public boolean isCreated = false;

	public CardType[][] mCards;
    public String[] mPeople;
    public String[] mPlace;
    public String[] mWeapon;

    public int cardnum = 24;
    public int playernum = 6;
    
    public ArrayList<PlayerPOJO> mPlayers;
	public ArrayList<PMovePOJO> mLogsList;
    
	
	public enum CardType {
		DEFAULT(0), NO(1), YES(2), QUESTION(3), ASK(4);

		private final int id;
		
		CardType(int id) {
			this.id = id;
		}

		public int getValue() {
			return id;
		}

		public static CardType findByOrdinal(int ordinal) {
			for (CardType item : values()) {
				if (item.ordinal() == ordinal) {
					return item;
				}
			}
			return DEFAULT;
		}
	}
	
	public enum ShowModeType {
		ALL(0), XODIT(1), PODTVERDIL(2), PEOPLE(3), PLACE(4), WEAPON(5);

		private final int id;
		
		ShowModeType(int id) {
			this.id = id;
		}

		public int getValue() {
			return id;
		}

		public static ShowModeType findByOrdinal(int ordinal) {
			for (ShowModeType item : values()) {
				if (item.ordinal() == ordinal) {
					return item;
				}
			}
			return ALL;
		}
	}

	public GamePOJO(){
		YourPlayer = 1; // default
		NumberOfPlayers = 3; // default
		
		//Default initialization
		mPeople = new String[playernum];
		mPlace = new String[9];
		mWeapon = new String[9];
		// all raws for list
		mCards  = new CardType[cardnum][playernum]; 
		
		for (int i=0;i<playernum;i++){
			for (int j=0; j<cardnum; j++){
				mCards[j][i] = CardType.DEFAULT;
			}
		}
		
		mPlayers = new ArrayList<PlayerPOJO>();
		mLogsList = new ArrayList<PMovePOJO>();
		
	}
	
	public void setVersion(int ver){
		version = ver;
	}
	
	public int getVersion(){
		return version;
	}
	
}
